export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${HOME}/.local/share"
export ZDOTDIR=${HOME}/.config/zsh
export HISTFILE=${XDG_DATA_HOME}/zsh/history
export SAVEHIST=10000	
export HISTSIZE=10000
export DIRSTACKSIZE=20
export LESSHISTFILE="-"
export GREP_COLOR='1;31'
export PAGER="less"
export READNULLCMD="${PAGER}"
export VISUAL="vim"
export EDITOR="${VISUAL}"
export MANPATH="/usr/share/man/ru:/usr/man:/usr/share/man:/usr/local/man:/usr/X11R6/man:/opt/qt/doc:usr/local/bin:"
export BLOCKSIZE=Mb
export WORDCHARS=':*?_-.[]~&;!#$%^(){}<>|'
export TERM="rxvt-256color"
export VIMINIT=":source $XDG_CONFIG_HOME"/vim/vimrc
export VIMPERATOR_INIT=":source $XDG_CONFIG_HOME/vimperator/vimperatorrc"
export VIMPERATOR_RUNTIME="$XDG_CONFIG_HOME"/vimperator
export MPLAYER_HOME="$XDG_CONFIG_HOME"/mplayer
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
